export default function About() {
  return (
    <div className='mt-36'>
      <h1 className='ml-48 grid grid-rows-4 text-5xl text-zanisk-sand'>
        <span>SO</span>
        <span>BR</span>
        <span>E</span>
      </h1>
      <p className='mx-auto mb-7 w-1/2 text-justify leading-loose tracking-widest text-zanisk-sand'>
        MEU NOME É LUCAS, TENHO 26 ANOS E COMECEI MEUS ESTUDOS NA ÁREA DE
        DESENVOLVIMENTO EM 2018, ATÉ ENTÃO POR CURIOSIDADE ENQUANTO CURSAVA
        ARQUITETURA E URBANISMO EM MANAUS-AM, COM O INTUITO DE NUM FUTURO
        CONCILIAR AS DUAS ÁREAS EM ALGUM PROJETO VOLTADO AO CURSO. PORÉM, EM
        CERTO MOMENTO, ME VI TOTALMENTE IMERSO NO MUNDO DA PROGRAMAÇÃO,
        DESENVOLVENDO EM PROJETOS COM AMIGOS, DESDE CONSTRUÇÕES DE RESTAPIS EM
        PYTHON À PÁGINAS WEB UTILIZANDO REACT. <br /> <br />
        EM 2020, PERCEBI QUE MEU REAL DESEJO ERA DESENVOLVER SOFTWARES E TORNEI
        COMO OBJETIVO PRINCIPAL CONSTRUIR MINHA CARREIRA NA ÁREA, SENDO ASSIM,
        MIGREI DE CURSO PARA ANÁLISE E DESENVOLVIMENTO DE SISTEMAS E BUSQUEI ME
        APERFEIÇOAR EM DESENVOLVIMENTO FRONTEND. <br />
        <br /> HOJE, EM 2022, TRABALHO COMO DESENVOLVEDOR FRONTEND EM UMA
        FINTECH NA CIDADE DE SÃO PAULO E MORO AQUI HÁ 1 ANO, CONQUISTAS ADVINDAS
        DESSE UNIVERSO QUE É A PROGRAMAÇÃO. HELLO WORLD!
      </p>
    </div>
  );
}
